name: miningAgent-env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - archspec=0.2.3
  - boltons=23.0.0
  - brotli-python=1.0.9
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.11.4
  - certifi=2025.11.12
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - conda=25.11.0
  - conda-libmamba-solver=25.4.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - cpp-expected=1.1.0
  - distro=1.9.0
  - expat=2.6.2
  - fmt=9.1.0
  - frozendict=2.4.2
  - icu=73.1
  - idna=3.7
  - jsonpatch=1.33
  - jsonpointer=2.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libarchive=3.7.7
  - libcurl=8.7.1
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libmamba=2.0.5
  - libmambapy=2.0.5
  - libnghttp2=1.57.0
  - libsolv=0.7.30
  - libssh2=1.11.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxml2=2.13.9
  - lz4-c=1.9.4
  - menuinst=2.0.2
  - ncurses=6.4
  - nlohmann_json=3.11.2
  - openssl=3.0.18
  - packaging=23.2
  - pcre2=10.42
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pyopenssl=25.0.0
  - pysocks=1.7.1
  - python=3.12.3
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.4
  - ruamel.yaml=0.17.21
  - setuptools=78.1.1
  - simdjson=3.10.1
  - spdlog=1.11.0
  - sqlite=3.45.3
  - tk=8.6.14
  - truststore=0.8.0
  - typing_extensions=4.15.0
  - tzdata=2024a
  - urllib3=2.5.0
  - wheel=0.43.0
  - xz=5.6.4
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
      - cryptography==43.0.1
      - pip==25.3
      - tqdm==4.66.3
prefix: /opt/conda
